services:

  portal:
    image: matheusraiano/viaserra-portal:1.0-26174983                # a imagem que você publicou na Parte 2 (usuario/nome:tag)
    ports:
      - "8083:80"              # porta do host: 8000 + XX
    restart: unless-stopped

  manutencao:
    build: manutencao                # a pasta onde está o Dockerfile que você corrigiu na Parte 3
    ports:
      - "7083:80"              # porta do host: 7000 + XX
    restart: unless-stopped
